version: '3.4'
services:
  filtering:
    build: ../
    volumes:
      - ./config:/config
    ports:
      - 8090:80
    environment:
      SERVER_PORT: "80"
      DEFAULT_APPLICATION_PROFILE_PATH: "file:/config/application-profile.ttl"
      SPARQL_ENDPOINT: "http://db:8890" # todo change that
      MAX_REQUEST_SIZE: "512MB"
      MAX_FILE_SIZE: "512MB"
      JAVA_OPTS: "-Xms512m -Xmx512m"
    restart: always
